[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
 
decorations = "Buttonless"

opacity = 1 
# blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMonoNL Nerd Font" 
normal.style = "Regular"
size = 15

